language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install flake8
  - pip install coveralls
script:
  - flake8 *.py
  - coverage run --branch --source koinenlp test.py
after_success:
  - coveralls